
    create table Atuendo (
        id bigint generated by default as identity (start with 1),
        accesorio_id bigint,
        calzado_id bigint,
        prendaInferior_id bigint,
        primary key (id)
    )

    create table Atuendo_Prenda (
        Atuendo_id bigint not null,
        prendasSuperiores_id bigint not null
    )

    create table Color (
        id bigint generated by default as identity (start with 1),
        azul integer,
        rgb varchar(255),
        rojo integer,
        verde integer,
        primary key (id)
    )

    create table Evento (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        fecha date,
        fechaUltimaInstancia date,
        tipoRecurrencia varchar(255),
        guardarropa_id bigint,
        usuario_id bigint,
        primary key (id)
    )

    create table Evento_Sugerencia (
        Evento_id bigint not null,
        sugerencias_id bigint not null
    )

    create table Guardarropa (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nombreGuardarropas varchar(255),
        primary key (id)
    )

    create table IgNotifier (
        idUsuario varchar(255),
        nombreUsuario varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table InteresEnNotificaciones (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table MAP_SENSIBILIDAD (
        Sensibilidad_id bigint not null,
        valor_sensiblidad integer,
        valores_KEY varchar(255),
        primary key (Sensibilidad_id, valores_KEY)
    )

    create table MailSender (
        destinatario varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Prenda (
        id bigint generated by default as identity (start with 1),
        tipoPrenda varchar(255),
        tipoTela varchar(255),
        colorPrimario_id bigint,
        colorSecundario_id bigint,
        guardarropa_id bigint,
        primary key (id)
    )

    create table Sensibilidad (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Sugerencia (
        id bigint generated by default as identity (start with 1),
        estado varchar(255),
        atuendo_id bigint,
        primary key (id)
    )

    create table Usuario (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        password varchar(255),
        username varchar(255),
        sensibilidad_id bigint,
        primary key (id)
    )

    create table Usuario_Guardarropa (
        Usuario_id bigint not null,
        guardarropas_id bigint not null,
        primary key (Usuario_id, guardarropas_id)
    )

    alter table Atuendo 
        add constraint FK_s2wr6v6h7ronxfe4x62vdkmq5 
        foreign key (accesorio_id) 
        references Prenda

    alter table Atuendo 
        add constraint FK_6of8s00cg4g8y8voehnxphd31 
        foreign key (calzado_id) 
        references Prenda

    alter table Atuendo 
        add constraint FK_pqt1ey962sgg2797xwk7gdans 
        foreign key (prendaInferior_id) 
        references Prenda

    alter table Atuendo_Prenda 
        add constraint FK_db6x7jeowaprrtdnpnjg3br5n 
        foreign key (prendasSuperiores_id) 
        references Prenda

    alter table Atuendo_Prenda 
        add constraint FK_cwj7rmf0ifrwmmmlktoq2wlh3 
        foreign key (Atuendo_id) 
        references Atuendo

    alter table Evento 
        add constraint FK_kvr6qwqw4dlr7qcppfkq5qtg1 
        foreign key (guardarropa_id) 
        references Guardarropa

    alter table Evento 
        add constraint FK_5tchfsc0poqtarjtn85vs9qpq 
        foreign key (usuario_id) 
        references Usuario

    alter table Evento_Sugerencia 
        add constraint FK_86sh03ceusjqbatdtvdj47wil 
        foreign key (sugerencias_id) 
        references Sugerencia

    alter table Evento_Sugerencia 
        add constraint FK_ayqwhutmoihuu5i5sip99p2u6 
        foreign key (Evento_id) 
        references Evento

    alter table IgNotifier 
        add constraint FK_qmxjvsf5lo1gau6p67kww3hd2 
        foreign key (id) 
        references InteresEnNotificaciones

    alter table InteresEnNotificaciones 
        add constraint FK_hvgtdgjmtrr600fe1jxt6gtd5 
        foreign key (id) 
        references Usuario

    alter table MAP_SENSIBILIDAD 
        add constraint FK_f71uqg4qh7lm3cmley9v2eiva 
        foreign key (Sensibilidad_id) 
        references Sensibilidad

    alter table MailSender 
        add constraint FK_gcm3njcl139daxot9hqlp2kyj 
        foreign key (id) 
        references InteresEnNotificaciones

    alter table Prenda 
        add constraint FK_jrdf7aapadjruojlh2fsmrelk 
        foreign key (colorPrimario_id) 
        references Color

    alter table Prenda 
        add constraint FK_1tr9mkbf3kh20v43s21nalb4u 
        foreign key (colorSecundario_id) 
        references Color

    alter table Prenda 
        add constraint FK_630jkg0qc00ifidtga99v3aop 
        foreign key (guardarropa_id) 
        references Guardarropa

    alter table Sugerencia 
        add constraint FK_ib92cmv89dv640xmtw3t2ysa4 
        foreign key (atuendo_id) 
        references Atuendo

    alter table Usuario 
        add constraint FK_hnfa40v19wqhwk6hjy6h7ro3p 
        foreign key (sensibilidad_id) 
        references Sensibilidad

    alter table Usuario_Guardarropa 
        add constraint FK_exvaq4sy1rbjcil7xs13w5xs2 
        foreign key (guardarropas_id) 
        references Guardarropa

    alter table Usuario_Guardarropa 
        add constraint FK_d02fvs98p85p43dex3uu6q7bs 
        foreign key (Usuario_id) 
        references Usuario
